# Generated by Django 6.1 on 2026-08-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusambassador',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
