# Generated by Django 6.1 on 2026-09-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_campusambassador_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('event_type', models.CharField(choices=[('workshop', 'Workshop'), ('competition', 'Competition'), ('daksha', 'Daksha')], max_length=20)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('poster', models.FileField(blank=True, upload_to='events/posters/')),
                ('details', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='campusambassador',
            name='referral_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='api.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
