

# Leaderboard
GET http://127.0.0.1:3025/api/ambassador/leaderboard/ HTTP/1.1
content-type: application/json


###


# To add points
POST http://127.0.0.1:3025/api/ambassador/add_points/ HTTP/1.1
content-type: application/json
Authorization: Api-Key <api_key>

{
    "referral_code": "GEC090"
}

###


# To add campus ambassodors
POST http://127.0.0.1:3025/api/ambassador/add/ HTTP/1.1
content-type: application/json
Authorization: Api-Key <api_key>

{
    "name": "John Abraham",
    "college": "GEC Thrissur",
    "referral_code": "GEC090"
}

###


# Events
GET http://127.0.0.1:3025/api/events/ HTTP/1.1
content-type: application/json


###


# Workshop events
GET http://127.0.0.1:3025/api/events/?type=workshop HTTP/1.1
content-type: application/json


###


# Competition events
GET http://127.0.0.1:3025/api/events/?type=competition HTTP/1.1
content-type: application/json


###


# Daksha events
GET http://127.0.0.1:3025/api/events/?type=daksha HTTP/1.1
content-type: application/json


###


# Featured events
GET http://127.0.0.1:3025/api/events/featured/ HTTP/1.1
content-type: application/json


###


# Event detail
GET http://127.0.0.1:3025/api/events/project-expo/ HTTP/1.1
content-type: application/json
