events {
    worker_connections 1024;
}

http {

    include /etc/nginx/mime.types;

    default_type application/octet-stream;

    sendfile on;

    keepalive_timeout 65;


    # =========================
    # React frontend
    # =========================

    upstream frontend {
        server client:80;
    }


    # =========================
    # Django backend
    # =========================

    upstream backend {
        server server:8000;
    }


    # =========================
    # Main application
    # =========================

    server {

        listen 80;

        server_name drishti.cet.ac.in;

        client_max_body_size 50M;


        # =========================
        # Django API
        # =========================

        location /api/ {

            proxy_pass http://backend;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # =========================
        # Django static files
        # =========================

        location /static/ {

            alias /app/staticfiles/;

            expires 1y;

            add_header Cache-Control "public, immutable";
        }


        # =========================
        # Django Admin
        # =========================

        location /admin/ {

            proxy_pass http://backend;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # =========================
        # Django media
        # =========================

        location /media/ {

            alias /app/media/;

            expires 30d;

            add_header Cache-Control "public";
        }


        # =========================
        # React frontend
        # =========================

        location / {

            proxy_pass http://frontend;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
